// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsPodoiS1pbobsS6SUAfg2vF9YOCFhDJo',
    appId: '1:228276973305:web:ca0bf82af6d717ecb2bc28',
    messagingSenderId: '228276973305',
    projectId: 'canteenapp-dd431',
    authDomain: 'canteenapp-dd431.firebaseapp.com',
    storageBucket: 'canteenapp-dd431.firebasestorage.app',
    measurementId: 'G-VDQZ6QDFV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhCCwuubu5CWU0XYRsOB-bMLI0SN09tnE',
    appId: '1:228276973305:android:e74421960e2ae5cdb2bc28',
    messagingSenderId: '228276973305',
    projectId: 'canteenapp-dd431',
    storageBucket: 'canteenapp-dd431.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClaXijjLkPeJdvBG3jsJBB4utlZgYd3Pw',
    appId: '1:228276973305:ios:22a60fd88da3a1c6b2bc28',
    messagingSenderId: '228276973305',
    projectId: 'canteenapp-dd431',
    storageBucket: 'canteenapp-dd431.firebasestorage.app',
    iosBundleId: 'com.example.canteenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClaXijjLkPeJdvBG3jsJBB4utlZgYd3Pw',
    appId: '1:228276973305:ios:22a60fd88da3a1c6b2bc28',
    messagingSenderId: '228276973305',
    projectId: 'canteenapp-dd431',
    storageBucket: 'canteenapp-dd431.firebasestorage.app',
    iosBundleId: 'com.example.canteenApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsPodoiS1pbobsS6SUAfg2vF9YOCFhDJo',
    appId: '1:228276973305:web:daf2b106b8b80771b2bc28',
    messagingSenderId: '228276973305',
    projectId: 'canteenapp-dd431',
    authDomain: 'canteenapp-dd431.firebaseapp.com',
    storageBucket: 'canteenapp-dd431.firebasestorage.app',
    measurementId: 'G-05P3ZF5RZ4',
  );
}
