import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';

import 'firebase_options.dart'; // generated by FlutterFire CLI

import 'screens/login/login_screen.dart';
import 'screens/register/register_screen.dart';
import 'screens/forgotpw/forgotpw.dart';
import 'screens/forgotpw/codeverification.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ✅ Initialize Firebase with correct options
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const CanteenApp());
}

class CanteenApp extends StatelessWidget {
  const CanteenApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Canteen App',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.amber,
        useMaterial3: true,
      ),

      // ✅ Define all routes in one place
      initialRoute: '/login',
      routes: {
        '/login': (_) => LoginScreen(),
        '/register': (_) => RegisterScreen(),
        '/forgot': (_) => const ForgotPWScreen(),
        '/check-email': (_) => const CodeVerificationScreen(),
      },
    );
  }
}
